import { Page, Locator, expect } from '@playwright/test';

export class EmployeePage {
  private readonly page: Page;

  //private readonly AdminMenu: Locator;
  private readonly PIMMenu: Locator;
  private readonly addEmployeeButton: Locator;
  
  private readonly roleDropdown: Locator;
  private readonly firstNameInput: Locator;
  private readonly lastNameInput: Locator;
  private readonly employeeId: Locator;
  private readonly saveButton: Locator;

  private readonly successToast: Locator;

  private readonly employeeTable: Locator;
  private readonly employeeListTab: Locator;
  private readonly employeeNameSearchInput: Locator;
  private readonly searchButton: Locator;
  private readonly editIcon: Locator;

  constructor(page: Page) {
    this.page = page;

    //this.AdminMenu = page.locator('a[href*="pim/viewAdminModule"]');
    this.PIMMenu = page.getByRole('link', { name: 'PIM' })
    this.addEmployeeButton = page.getByRole('button', { name: /Add/i })

    this.roleDropdown  = page.locator('.oxd-select-text');

    this.firstNameInput = page.locator('input[name="firstName"]');
    this.lastNameInput = page.locator('input[name="lastName"]');
    this.employeeId = page.locator('form .oxd-input-group input').nth(3);


    this.saveButton = page.locator('button[type="submit"]');

    this.successToast = page.locator('.oxd-toast-content');

    this.employeeTable = page.locator('.oxd-table-body');

    this.employeeListTab = page.locator('a[href*="pim/viewEmployeeList"]');

    this.employeeNameSearchInput = page.locator('input[placeholder="Type for hints..."]');
    this.searchButton = page.locator('button:has-text("Search")');
    this.editIcon = page.locator('i.bi-pencil-fill');
  }

  async navigateToAddEmployee() {
    await this.PIMMenu.click();
    // Wait for the page to navigate to PIM section
    await this.page.waitForURL(/pim/i, { timeout: 30000 });
    await this.page.waitForLoadState('domcontentloaded');
    // Now wait for and click the Add button
    await this.addEmployeeButton.click();
    await expect(this.firstNameInput).toBeVisible();
  }

  async createEmployee(firstName: string, lastName: string) {
    await this.firstNameInput.fill(firstName);
    await this.lastNameInput.fill(lastName);
    
    // Do NOT fill Employee ID - it will be auto-generated by the application
    
    // Wait for any form loader to disappear before clicking save
    const formLoader = this.page.locator('[data-v-d5bfe35b]'); // Form loader element
    await formLoader.waitFor({ state: 'hidden', timeout: 10000 }).catch(() => {
      // Loader might not exist, that's ok
    });
    
    await this.saveButton.click();
    await expect.soft(this.successToast).toBeVisible();
  }

  async getPrefilledEmployeeIdFromForm(): Promise<string> {
    /**
     * Extracts the pre-filled Employee ID from the form input field.
     * The Employee ID field is dynamically populated after creating an employee.
     * 
     * Locator strategy: Find the input that is within the "Employee Id" label container
     */
    const employeeIdInput = this.page.locator(
      '.oxd-input-group:has(label:has-text("Employee Id")) input'
    );
    
    await expect(employeeIdInput).toBeVisible();
    const empId = await employeeIdInput.inputValue();
    return empId?.trim() || '';
  }

  async getAutoGeneratedEmployeeId(): Promise<string> {
    // After successful creation, navigate to employee list to read the auto-generated ID
    // Click PIM menu first, then Employee List link
    await this.PIMMenu.click();
    await this.page.waitForLoadState('domcontentloaded');
    
    // Click Employee List from the topbar menu
    await this.page.getByRole('link', { name: 'Employee List' }).click();
    await this.page.waitForLoadState('domcontentloaded');
    
    // The most recently created employee should be visible in the list
    // Wait for table to load
    await expect(this.employeeTable).toBeVisible();
    
    // Get the first employee row's ID (Employee ID column is the 2nd column)
    const firstEmployeeId = this.employeeTable
      .locator('.oxd-table-row')
      .first()
      .locator('.oxd-table-cell')
      .nth(1);
    
    await expect(firstEmployeeId).toBeVisible();
    const empId = await firstEmployeeId.textContent();
    return empId?.trim() || '';
  }


  async openEmployeeFromList(empID: string) {
    // Navigate to employee list via PIM menu
    await this.PIMMenu.click();
    await this.page.waitForLoadState('domcontentloaded');
    
    // Click Employee List from the topbar menu
    await this.page.getByRole('link', { name: 'Employee List' }).click();
    await this.page.waitForLoadState('domcontentloaded');

    // Find the row containing the specific Employee ID
    const tableBody = this.page.locator('.oxd-table-body');
    const employeeRow = tableBody.locator('.oxd-table-row').filter({
      has: this.page.locator('.oxd-table-cell', {
        hasText: empID,
      }),
    });

    await expect(employeeRow).toBeVisible();
    
    // Click the edit (pencil) icon in the matching row
    await employeeRow.locator('i.bi-pencil-fill').click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async updateFirstName(newFirstName: string) {
    await expect(this.firstNameInput).toBeVisible();

    await this.firstNameInput.fill('');
    await this.firstNameInput.fill(newFirstName);

    await this.saveButton.click();
    await expect(this.successToast).toBeVisible();
  }
}
